# Første linje
examples: brucite_in_water

.PHONY: brucite_in_water
brucite_in_water: brucite_in_water/brucite_in_water_orthogonal.png brucite_in_water/brucite_in_water_perspective.png


brucite_in_water/brucite_in_water_orthogonal.png brucite_in_water/brucite_in_water_perspective.png: brucite_in_water/brucite_in_water.py
	cd brucite_in_water && python brucite_in_water.py && cd ..



all: examples

