# Første linje
getting_started: python/alpha_quartz.png python/beta_cristobalite.png

python/alpha_quartz.png:
	cd python && python bulk_alpha_quartz.py && cd ..

python/beta_cristobalite.png:
	cd python && python bulk_beta_cristobalite.py && cd ..

all: getting_started

